#! /bin/bash

# set -o xtrace

name="nanogenmo_2021"
checkpoint_numbers=$(ls cv/*.t7 | cut -d'_' -f4- | sort -n | head -n10) # get best checkpoints (might be overfit)
checkpoint_number=$(echo -e "$checkpoint_numbers" | shuf -n1) # get one of the best checkpoints (might be overfit)
checkpoint=$(ls cv/*$checkpoint_number)

docker restart "$name" || docker run -dt -v "$(pwd)"/cv:/home/char-rnn/cv -v "$(pwd)"/training-data:/home/char-rnn/data/my-training-data --name "$name" mbartoli/char-rnn /bin/bash

if [[ $1 =~ "train" ]]; then
   if [[ $checkpoint ]]; then
      docker exec -it "$name" bash -lc "th train.lua -data_dir data/my-training-data -rnn_size 512 -num_layers 2 -dropout 0.5 -init_from $checkpoint"
   else
      docker exec -it "$name" bash -lc "th train.lua -data_dir data/my-training-data -rnn_size 512 -num_layers 2 -dropout 0.5"
   fi;
fi;

[[ $1 =~ "generate" ]] && docker exec -it "$name" bash -lc "th sample.lua cv/$(ls -t cv | head -n1)"

if [[ $1 =~ "gen" || $1 =~ "all || $1 =~ "all"" ]]; then
   # TODO make continue function that runs sample.lua with -init_from
   docker exec -it "$name" bash -lc "th sample.lua ${@:2} \"$checkpoint\""
fi;

if [[ $1 =~ "make" ]]; then
   docker exec -it "$name" bash -lc "th sample.lua -temperature 0.5 \"$checkpoint\"" | tail -n +7 > output.txt
   echo "init cp: $checkpoint"
   counter=$(wc -w output.txt | cut -d' ' -f1)
   while [ $counter -le 50000 ]; do
      checkpoint_number=$(echo -e "$checkpoint_numbers" | shuf -n1) # get one of the best checkpoints (might be overfit)
      checkpoint=$(ls cv/*$checkpoint_number)
      seed=$(tail -n 50 output.txt | node ./phrase_finder.js | shuf -n1 | sed 's!/.!\U&!g')
      echo "cp: $checkpoint"
      echo "seed: $seed"
      if  (( $counter % 4000 <= 300 )) || (( $counter % 4000 >= 3700 )); then
         chapter=$(echo $seed  | sed 's!/.!\U&!g')
         echo "chapter: $chapter"
         echo -e "\n\n\\\chapter{$chapter}\n\n" >> output.txt
      else
         echo -e "\n\n"
      fi
      docker exec -it "$name" bash -lc "th sample.lua -temperature 0.5 -primetext \"$seed\" \"$checkpoint\"" | tail -n +7 >> output.txt
      counter=$(wc -w output.txt | cut -d' ' -f1)
      echo "length: $counter"
   done;
   title=$(cat output.txt | node ./phrase_finder.js | shuf -n1 | sed 's!/.!\U&!g')
   echo -e "\\\title{$title}\n\n$(cat output.txt)" > output.txt
   filename=$(echo $title | perl -pe 's/[:;,\?\[\]\/\\=<>''"&\$#*()|~`!{}%+]//g; s/[\s-]+/-/g;')
   echo "title: $title"
   echo "filename: $filename"
   pandoc -s \
      --from markdown-smart \
      --toc \
      --wrap=preserve \
      --pdf-engine=xelatex \
      -o output/$filename \
      output.txt
fi;
